name = "Detangle"
uuid = "b23e9bf5-c030-48ea-90eb-85d026696f85"
authors = ["eswagel <73608467+eswagel@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
